### ISSUE TITLE
Ligatures not rendering

### ISSUE THREAD

**Issue by dragondgold** [opentypejs/opentype.js#479] opened 2021-06-23 19:11 UTC
## Expected Behavior
The font should be rendered with ligatures:
![image](https://user-images.githubusercontent.com/2932540/123132598-49aec100-d425-11eb-80a4-b087c82bb235.png)

## Current Behavior
The font is rendered without ligatures, although they are being detected in the `gsub` table as far as I understand:

![image](https://user-images.githubusercontent.com/2932540/123133111-ca6dbd00-d425-11eb-8667-12ed7fe21c42.png)

![image](https://user-images.githubusercontent.com/2932540/123132630-5206fc00-d425-11eb-815f-50f04738440b.png)

## Possible Solution
I don't know actually, I don't have much experience on the font file internals, but I'm open to working on the issue if someone is willing to guide me a little

## Steps to Reproduce (for bugs)
1. Go to https://opentype.js.org/
2. Upload the TTF font [Pecita.zip](https://github.com/opentypejs/opentype.js/files/6703435/Pecita.zip)
3. Make sure ligatures are enabled
4. Write the word "quick" or any other word, the font is not rendered with ligatures

## Context
I have an app where users can write text on the browser using any font and export the text as SVG, it works great for most fonts, some of them have issues, converting them from TTF to OTF or vice-versa or re-exporting them with FontForge fixes most issues, in this case, I couldn't fix the issue by doing that in this case.

## Your Environment
* Version used: Opentype.js 1.3.1
* Font used: [Pecita.zip](https://github.com/opentypejs/opentype.js/files/6703435/Pecita.zip)
* Browser Name and version: Chrome Version 91.0.4472.114
* Operating System and version (desktop or mobile): Windows 10 21H1 x64

**Comment by ILOVEPIE** [comment] 2023-02-03 01:43
You have to ask opentype.js to use ligatures, by default it does not.

**Comment by Connum** [comment] 2023-02-05 13:17
As it says "make sure ligatures are enabled" in the steps to reproduce, I think we need to look into this. Or did you try it out and it worked on your end @ILOVEPIE? In that case it might have been fixed in the meantime, as the issue is already 2 years old.

**Comment by ILOVEPIE** [comment] 2023-02-05 21:21
The cause of this has been determined, I've created a new issue with the specific information on the bug, we will move discussion of this issue to there.

**Closed by ILOVEPIE** 2023-02-05 21:21 UTC
Labels: bug, Needs Investigation
