### ISSUE TITLE
noto load/save problem with glyphNames

### ISSUE THREAD

**Issue by jeromew** [opentypejs/opentype.js#240] opened 2016-11-11 10:24 UTC
Hello,

I am trying to work with opentype.js and the noto fonts.
The font I use in this example is "NotoSansTagbanwa-Regular.ttf" available in https://noto-website-2.storage.googleapis.com/pkgs/NotoSansTagbanwa-unhinted.zip but the problem also happens with the other noto ttf files.

Basically, the following example outputs an error

```
var opentype = require('opentype.js');
opentype.load("NotoSansTagbanwa-Regular.ttf", function(err, font) {
  if (err) { console.log(err) }
  else {
    font.toArrayBuffer()
  }
})

```

leads to

> /home/x/tmp/noto/node_modules/opentype.js/src/types.js:75
>    for (var i = 0; i < v.length; i += 1) {
>                         ^
> TypeError: Cannot read property 'length' of undefined
>     at encode.CHARARRAY (/home/x/tmp/noto/node_modules/opentype.js/src/types.js:75:26)
>     at Object.encode.OBJECT (/home/x/tmp/noto/node_modules/opentype.js/src/types.js:764:12)
>     at Object.encode.INDEX (/home/x/tmp/noto/node_modules/opentype.js/src/types.js:603:24)
>     at sizeOf.INDEX (/home/x/tmp/noto/node_modules/opentype.js/src/types.js:632:19)
>     at Object.sizeOf.TABLE (/home/x/tmp/noto/node_modules/opentype.js/src/types.js:840:21)
>     at Table.sizeOf (/home/x/tmp/noto/node_modules/opentype.js/src/table.js:50:19)
>     at Object.makeCFFTable [as make] (/home/x/tmp/noto/node_modules/opentype.js/src/tables/cff.js:1095:23)
>     at Object.fontToSfntTable [as fontToTable] (/home/x/tmp/noto/node_modules/opentype.js/src/tables/sfnt.js:293:24)
>     at Font.toTables (/home/x/tmp/noto/node_modules/opentype.js/src/font.js:379:17)
>     at Font.toArrayBuffer (/home/x/tmp/noto/node_modules/opentype.js/src/font.js:393:26)
> 

I drilled down on this issue, and it seems to happen because after loading the font, the glyph names are undefined.

The `font.glyphNames.names` array exists and is empty because `post.version = 3`

I observed the code path in encoding.js 
```
function addGlyphNames(font) {
    var glyph;
    var glyphIndexMap = font.tables.cmap.glyphIndexMap;
    var charCodes = Object.keys(glyphIndexMap);

    for (var i = 0; i < charCodes.length; i += 1) {
        var c = charCodes[i];
        var glyphIndex = glyphIndexMap[c];
        glyph = font.glyphs.get(glyphIndex);
        glyph.addUnicode(parseInt(c));
    }

    for (i = 0; i < font.glyphs.length; i += 1) {
        glyph = font.glyphs.get(i);
        if (font.cffEncoding) {
            glyph.name = font.cffEncoding.charset[i];
        } else if (font.glyphNames.names) {
            glyph.name = font.glyphNames.glyphIndexToName(i);
        }
    }
}

```

and we hit `glyph.name = font.glyphNames.glyphIndexToName(i);` which answers undefined because the array is empty.

then the `CHARARRAY` crashes because it does not know how to serialize undefined.

I would be happy to propose a PR for this but I don't know what would be the best spec-friendly fix. I don't know how to verify if the names exist in the original .ttf, if it is correct or not that a ttf could be created without glyph names, nor if it is acceptable to create a font with empty glyph names

for instance, if the code is modified with

```
        if (font.cffEncoding) {
            glyph.name = font.cffEncoding.charset[i];
        } else if (font.glyphNames.names && font.glyphNames.names.length) {
            glyph.name = font.glyphNames.glyphIndexToName(i);
        } else {
            glyph.name = '';
        }

```

then the load/save cycle works but the fix is maybe too spec-preemptive. There seem to be other problems with the load/save cycle of other noto fonts. When I add the patch above and use the test on `NotoSans-Regular.ttf` I avoid the same problem but then I hit

> /home/x/tmp/noto/node_modules/opentype.js/src/check.js:6
>     throw new Error(message);
>     ^
> Error: Unable to write GSUB lookup type 7 tables.
>     at Object.exports.fail (/home/x/tmp/noto/node_modules/opentype.js/src/check.js:6:11)
>     at Object.exports.argument (/home/x/tmp/noto/node_modules/opentype.js/src/check.js:13:17)
>     at /home/x/tmp/noto/node_modules/opentype.js/src/table.js:180:15
>     at tableList (/home/x/tmp/noto/node_modules/opentype.js/src/table.js:76:68)
>     at new LookupList (/home/x/tmp/noto/node_modules/opentype.js/src/table.js:178:41)
>     at Object.makeGsubTable [as make] (/home/x/tmp/noto/node_modules/opentype.js/src/tables/gsub.js:253:49)
>     at Object.fontToSfntTable [as fontToTable] (/home/x/tmp/noto/node_modules/opentype.js/src/tables/sfnt.js:312:26)
>     at Font.toTables (/home/x/tmp/noto/node_modules/opentype.js/src/font.js:379:17)
>     at Font.toArrayBuffer (/home/x/tmp/noto/node_modules/opentype.js/src/font.js:393:26)
> 

Thanks for your feedback !

**Comment by jeromew** [comment] 2016-11-12 17:13
Regarding the GSUB type 7 I understood in the code that it is not implemented yet so this is a different problem.

Regarding the glyph names, I saw on https://github.com/fonttools/fonttools that they have the following algorithm:

The glyph names are either extracted from the CFF table or the post table, or are derived from a Unicode cmap table. In the latter case the Adobe Glyph List is used to calculate names based on Unicode values. If all of these methods fail, names are invented based on GlyphID (eg glyph00142)

if this makes sense, we could probably use the same algorithm in opentype.js, the Adobe Glyph List beeing referenced on https://en.wikipedia.org/wiki/Adobe_Glyph_List

**Comment by Jolg42** [comment] 2016-11-12 18:43
Hi @jeromew 

Yes the GSUB 7 is not yet implemented like you can see.

And you're right for the glyph names the best would be to match the Adobe Glyph List from this repository: https://github.com/adobe-type-tools/agl-aglfn

In fact the algorithm is explained here: https://github.com/adobe-type-tools/agl-specification#2-the-mapping
If no match, I think that we can name the glyphs "u" + hexadecimal value, like "u0061".
The "u" version (not "uni") looks better because it's ready for all Unicode area planes (0 to 16!)

I was using this mapping on my side if you're interested https://gist.github.com/Jolg42/a34bcde83c99b5a2823fcc9de4f12616

Used like this
```
function getNameForUnicode(unicode) {
    return unicodeNamesBasicPlane[unicode] || 'u' + unicode.toString(16);
}
```
I did not found the time to implement it in OpenType.js yet, so feel free to contribute to the project 😉

**Comment by jeromew** [comment] 2016-11-14 17:27
Ok I will work on a PR for this. There is something that I do not quite understand.
https://github.com/adobe-type-tools/agl-specification#2-the-mapping explains how to convert from a glyphName to a character or a sequence of code points.

In the code https://github.com/nodebox/opentype.js/blob/master/src/encoding.js#L251 the bug I saw was in `addGlyphNames`. I understand that I should write a reverse algorithm for what is written in adobe-type-tools algo (go from the point codes to the glyphName).

but what is supposed to be found in `font.cffEncoding.charset` and `font.glyphNames.names` ? I think a miss some background on fonts (cff, post v3, ..).

+ why is it necessary to derive glyphNames if there could not be found in the .ttf ? is it because we output .otf in opentype.js and opentype requires glyphNames ?

**Comment by Jolg42** [comment] 2016-11-14 18:50
Yes I see.

So in fact it's not mandatory to rebuild the glyphs names if you are reading a font.

I was using my code from the last comment because I was doing reads and writes, and when you export/write the font you need to put the correct glyphs names because some printers for example will have a hard time finding some glyphs.

I think that finding the glyph name and assigning it needs in fact to be done only when creating a font (not reading).

For your problem we just need to fix the reading bug but I didn't had time to check what's happening.

**Comment by jeromew** [comment] 2016-11-14 21:05
@Jolg42 ok I understand that glyphNames ought to be generated when creating a font to help downstream consumers and that is where keeping the algo compatible with the adobe algo is important.

Indeed you are right, the noto fonts, when loaded into opentype.js, lead to undefined glyphNames, which is weird, but I have no idea whether these glyphNames should be "found" inside the .ttf or built by an algorithm.  I will try a look a bit more at the specs to see if I find something.

The closest I have found is in https://www.microsoft.com/typography/otspec/post.htm because the font has a post version 3

> Version 3.0
> The version makes it possible to create a font that is not burdened with a large 'post' table set of glyph names. A version 3.0 'post' table can be used by OpenType fonts with TrueType or CFF (version 1 or 2) data.
> This version specifies that no PostScript name information is provided for the glyphs in this font file. The printing behavior of this version on PostScript printers is unspecified, except that it should not result in a fatal or unrecoverable error. Some drivers may print nothing; other drivers may attempt to print using a default naming scheme.

digging a little more, I see that noto fonts do not have a CFF table (which would mean that they only have a TrueType outline and no PostScript outline according to https://www.microsoft.com/typography/otspec/otff.htm)

The bug appears when opentype.js tries to generate a CFF table for the font. It crashes because it does not have the necessary glyph names.

now why do we try to generate a CFF table when there was no CFF table to begin with I have only a small idea. It appears that we generate a font with a sfntVersion = "OTTO" (the value is hardcoded - https://github.com/nodebox/opentype.js/blob/master/src/tables/sfnt.js#L57) and https://www.microsoft.com/typography/otspec/otff.htm says

>> OpenType fonts containing CFF data (version 1 or 2) should use the tag 'OTTO' for sfntVersion.

so that means at least that we we generate the font, we always want to output CFF data and there is no case that handles things differently.

But the font is a TrueType font because we hit the code on https://github.com/nodebox/opentype.js/blob/master/src/opentype.js#L183 and we have sfntVersion = 0x00010000

So this would explain the bug : we always try to generate a sfntVersion = OTTO font with embedded postscript outline (this is hardcoded) even when the font was originally loaded with sfntVersion = 0x00010000 without a postscript outline.

I am not sure what to do with all this. If you have enough knowledge on opentype.js an can guide me to an acceptable solution I would be interested.

Maybe use the "font.outlinesFormat" when exporting to decide which tables should land in the exported version ?

**Comment by halmos** [comment] 2018-01-10 14:27
For what's it worth I've managed to workaround this issue buy checking all the glyph names that are undefined and setting them before saving the font:

```js
for (let i = 0; i < font.glyphs.length; i++) {
      let glyph = font.glyphs.get(i);
      if (glyph.name == undefined) glyph.name = `u${glyph.unicode}`;
    }
```

but look forward to having this bug resolved.

**Comment by littlee** [comment] 2019-08-08 02:33
I getting the same error when working with ttf files
```
TypeError: Cannot read property 'length' of undefined
push../node_modules/opentype.js/src/types.js.encode.CHARARRAY
node_modules/opentype.js/src/types.js:76

  73 | encode.CHARARRAY = function (v) {
  74 |   const b = [];
  75 | 
> 76 |   for (let i = 0; i < v.length; i += 1) {
  77 |     b[i] = v.charCodeAt(i);
  78 |   }
  79 | 
```

**Comment by Connum** [comment] 2020-10-19 17:33
I just created PR #451 as a draft. I would like to discuss whether it's OK to simply address the symptom and not the cause. I haven't been able to find out whether unset glyph names are OK according to the OpenType spec or not. It also seems to me that sometimes glyphs turn out with an `undefined` name despite them having a name when instpecting them with FontForge, for example. But I don't know whether FontForge also implements this kind of defering the name from a glyph list.

**Closed** 2020-11-08 18:52 UTC
