### ISSUE TITLE
TTF not contains name and cmap table parse error

### ISSUE THREAD

**Issue by i2534** [opentypejs/opentype.js#370] opened 2019-02-14 09:13 UTC
like title,  I parse some ttf maybe from some pdf file, they are not found name and cmap table. so opentype.js throw error
I can open them using fontforge
[font_21.zip](https://github.com/opentypejs/opentype.js/files/2864117/font_21.zip)

**Comment by Connum** [comment] 2023-11-23 07:26
Closing as a duplicate of #643 - I'm working on restructuring the error handling in order to be able to load incomplete fonts and some font formats unsupported so far. You can check out the work-in-progress branch that will allow parsing this font:
https://github.com/Connum/opentype.js/tree/WIP/validation-error-handling

![image](https://github.com/opentypejs/opentype.js/assets/13076806/eaa71b60-b63a-4855-b798-24316e240bcd)

**Closed by Connum** 2023-11-23 07:26 UTC
