### ISSUE TITLE
Async await not working in typescript

### ISSUE THREAD

**Issue by noobd3v** [opentypejs/opentype.js#532] opened 2022-12-20 10:40 UTC
## Current Behavior
trying to use the async await as per the readme but its not returning the font object.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/13329441/208647664-0640ebfc-abc2-40fb-8766-0d998b1e8538.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Font used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by Connum** [comment] 2023-02-06 08:25
We need more information on this. I can't reproduce this issue running the current master on Node 16.
If it's not returning the font object, what else is it returning? Are there any error messages in the console?
There are red lines underneath the function calls in yous screenshots, what do the hints say?

**Comment by Connum** [comment] 2023-02-17 10:29
Closing this issue due to not being able to reproduce and no reaction.

**Closed by Connum** 2023-02-17 10:29 UTC
Labels: bug
