### ISSUE TITLE
Fill Path instead of stroke path

### ISSUE THREAD

**Issue by kpomservices** [opentypejs/opentype.js#488] opened 2021-08-25 11:31 UTC
Thanks for the library to get the bézier path for the text.
Currently we get the stroke bézier path for the text, is there is any way to get the fill path bézier data of the text?

Currently for any font getting the stroke path 
![image](https://user-images.githubusercontent.com/1684160/130782944-e74c00ef-445b-4902-acff-0f5c4defc32b.png)

but what i need is the inner / fill path of the letter
![image](https://user-images.githubusercontent.com/1684160/130782962-4beecc80-0699-462f-980e-2ab4d7d8f2e2.png)

Please suggest how to get the inner/fill bezier path of the text?

**Comment by axkibe** [comment] 2021-08-31 09:44
I don't get the issue, if you want the letter to be filled, use fill() call of canvas..

**Comment by kpomservices** [comment] 2021-09-01 17:13
Yes i can change the fill color, but I need the bezier path information of that fill area,

I am trying to animate the bezier path of the letter / text, currently its animating the path of the stroke path.
But i need to animate the fill section so that it look like hand-writing animation.

**Comment by danmarshall** [comment] 2021-12-07 04:28
Related: #434

**Comment by axkibe** [comment] 2022-02-07 07:32
I see, this is not something that can easily be computed even only approximated and IMO beyond the scope of this library.

I don't think an opentype/truetype font is something you should use in a usecase like this, because they are constructed differently as you found out. You need a font system that is "stroked" by design or just do the paths manually and avoid font systems all together.

**Comment by Connum** [comment] 2023-02-05 12:32
I would agree that this is outside of the scope of what opentype is intended for. A comment in #434 links to a possible solution for this.
I'd suggest closing this and #434 @ILOVEPIE

**Comment by ILOVEPIE** [comment] 2023-02-06 19:47
The stroke and fill path should be the same.

**Closed** 2023-11-25 18:39 UTC
